### ISSUE TITLE
Implementar rota que permita retirar um pokémon de venda

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#11]
## Description
Pode ocorrer de que um certo Pokémon não possa ser mais vendido em nossa plataforma, talvez ele esteja em risco de extinção, ou tenha sua venda proibida. Nesse contexto é necessário habilitar a possibilidade de retirar o monstrinho de venda.
Essa rota deverá receber o id do Pokémon, e desde que ele exista realizar um soft delete na tabela.

## Additional context
- **Rota: `DELETE /pokemon/:poke_id/del`**

## Tasks
- [x] Criar interface de comunicação com o banco
- [x] Implementar lógica no `service`
- [x] Implementar método no `controller`
- [x] Configurar a rota no `router`
- [ ] Atualizar `CHANGELOG.md`
