### ISSUE TITLE
Implementar rota de Login na plataforma

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#16]
## Description
Nessa tarefa desse implementado alguma forma de login para os usuários da plataforma, tanto ADM, quanto clientes.  Esse login será feito via e-mail e senha, gerando no final tokens de sessão. 
Para realizar o login pode-se utilizar os meios de autenticação fornecidos pelo supabase.

## Additional context
- [Supabase Auth](https://supabase.com/docs/guides/auth)

## Tasks
- [x] Implementar novo recurso de autenticação.
- [x] Implementar lógica de login
- [x] Implementar handler no controller
- [x] Criar rota: `POST /login`
- [x] Atualizar `CHANGELOG.md`
