### ISSUE TITLE
Implementar listagem dos Tiers existentes

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#27]
## Description
Tanto para critérios de informação dos clientes, quanto na hora de cadastrar um novo pokémon, é necessário poder visualizar os tiers cadastrados na plataforma.
Nesse contexto serão criadas duas rotas. A rota `/tiers` deverá listar todos os `Tiers` cadastrados e não excluídos da plataforma. Já a rota `/tiers/{id}` deverá retornar um `Tier` específico.

## Tasks

- [x] Criar interface de comunicação com o banco
- [x] Implementar lógica no `service`
- [x] Implementar método no `controller`
- [x] Configurar a rota no `router`
- [ ] Atualizar `CHANGELOG.md`
