### ISSUE TITLE
Implementar rota que possibilite o cadastro de um usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#3]
## Description

Será necessário que novos usuários possam se cadastrar na plataforma.  Para isso será criada uma rota `POST, /user/new`, que receberá no `body` da requisição o nome, email, data de nascimento e telefone do novo usuário.  
**Para criar uma conta o usuário deve ser maior de 18 anos, possuir um email, nome e telefone válidos.  A única restrição do nome é possuir mais de 3 caracteres.**
Acerca do tratamento de erros, problemas relacionados as entradas retornam `400 BAD REQUEST`. Já caso ocorra algum problema durante a inserção, como violação das restrições no banco, pode-se voltar `500 INTERNAL SERVER ERROR`. É uma boa prática não detalhar qual campo está se repetindo.  

## Additional context
- EPIC: #1 
- A lógica será feita no `service`.
- O `controller` será responsável por receber a requisição e acionar o `service`.

## Tasks
- [x] Criar interface de comunicação com o banco
- [ ] Implementar lógica no `service`
- [ ] Implementar método no `controller`
- [ ] Configurar a rota no `router`
- [ ] Atualizar `CHANGELOG.md`
