### ISSUE TITLE
Implementar busca do carrinho de compra de um usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#37]
## Description
O carrinho é o local onde os itens de um usuário ficam armazenados até ele finalizar sua compra. Nesse contexto é necessário implementar uma listagem que busque pelo último carrinho ativo de um cliente. Caso ele não tenha nenhum, nada é retornado.
Caso haja um carrinho será retornada suas informações base como também os itens dentro dele.

## Additional context
- **Um carrinho está ativo quando sua data de expiração ainda não estourou**

## Tasks

- [x] Criar contratos relacionadas ao módulo de carrinho.
- [x] Implementar interface de comunicação com o banco.
- [x] Implementar lógica no service
- [x] Implementar chamada no controller.
- [x] Implementar rota: `/users/:id/cart`
- [x] Atualizar `CHANGELOG.md`
