### ISSUE TITLE
Implementar adição de um item ao carrinho de compras

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#38]
## Description
Sempre que um cliente deseja adicionar um novo Pokémon ao seu carrinho será seguida a seguinte lógica:
1. O Pokémon existe e a quantidade solicitada não é superior ao estoque.
2. Busca-se pelo último carrinho ativo do usuário, caso não exista, cria-se um novo.
3. O preço do Pokémon é somado ao total do carrinho.
4. Um novo item é criado, relacionando-se com o preço atual do Pokémon, o Pokémon e a quantidade pedida.

### Body
```json
{
	"pokemon_id": "string",
	"price_id": "string",
	"quantity": 0,
}
```

## Tasks

- [x] Implementar interface de comunicação com o banco.
- [x] Implementar lógica no service
- [x] Implementar chamada no controller.
- [x] Implementar rota: `/users/:user_id/items/add`
- [x] Atualizar `CHANGELOG.md`
