### ISSUE TITLE
Implementar remoção de um item do carrinho de compras

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#39]
## Description
Pode ocorrer de um cliente mudar de ideia e desejar remover um `Item` do seu carrinho. Nesse cenário deve-se **apagar (`hard-delete`)** o item do banco e decrementar seu valor total do total do carrinho.  
O motivo do hard-delete é que um item que um usuário não deseja não tem qualquer valor para histórico.

## Additional context
- **Trabalhar dentro do módulo de `itens`**

## Tasks

- [x] Implementar interface de comunicação com o banco.
- [x] Implementar lógica no service
- [x] Implementar chamada no controller.
- [x] Implementar rota: `DELETE /carts/:cart_id/items/:item_id`
- [x] Atualizar `CHANGELOG.md`
