### ISSUE TITLE
Implementar rota que permita a atualização das informações de um usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#4]
## Description

Um usuário ao acessar seu perfil talvez deseje realizar a alteração de alguma de suas informações.  Para isso será criada uma rota `PATCH, /user/:user_id/update`, que receberá por parâmetro o `id do usuário`. Já no `body` da requisição serão enviados, sempre opcionalmente, o nome, email e telefone.  
Para os dados ficam vigentes as seguintes restrições:
- O id deve ser um `uuid` válido.
- O `email` deve ser válido e não haver nenhum outro usuário cadastrado o utilizando.
- O `telefone` deve ser válido e único.
- O nome deve possuir mais de três caracteres.
Acerca do tratamento de erros, problemas relacionados as entradas retornam `400 BAD REQUEST`. Já caso ocorra algum problema durante a atualização, como violação das restrições no banco, pode-se voltar `500 INTERNAL SERVER ERROR`. É uma boa prática não detalhar qual campo está se repetindo.  

## Additional context
- EPIC: #1 
- A lógica será feita no `service`.
- O `controller` será responsável por receber a requisição e acionar o `service`.

## Tasks
- [x] Criar interface de comunicação com o banco (implementado em: 669a62a747d45f43933e256698bbad014bb326a9)
- [x] Implementar lógica no `service`
- [x] Implementar método no `controller`
- [x] Configurar a rota no `router`
- [x] Atualizar `CHANGELOG.md`
