### ISSUE TITLE
Implementar finalização de compra

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#44]
## Description
Quando um cliente desejar finalizar sua compra, será obtido todos os itens do carrinho e linká-los com a compra, apagando o carrinho logo em seguida.

## Additional context
- **Trabalhar dentro do módulo de compra**

### Body
```json
{
	"cart_id": string,
	"user_id": string,
}
```

## Tasks

- [x] Implementar interface de comunicação com o banco.
- [x] Implementar lógica no service
- [x] Implementar chamada no controller.
- [ ] Implementar rota: `POST /purchase/finish`
- [ ] Atualizar `CHANGELOG.md`
