### ISSUE TITLE
Implementar listagem do histórico de compras do usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#45]
## Description

Um usuário deve poder visualizar todas as compras que ele já fez, mostrando as informações da compra e de seus itens.

## Additional context
- **Trabalhar dentro do módulo de compras**

## Tasks

- [x] Implementar interface de comunicação com o banco.
- [x] Implementar lógica no service
- [x] Implementar chamada no controller.
- [x] Implementar rota: `GET /purchases/:user_id`
- [x] Atualizar `CHANGELOG.md`
