### ISSUE TITLE
Implementar rota para excluir um usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#5]
## Description

Um usuário pode estar insatisfeito com a plataforma e desejar excluir sua conta. Para possibilitar isso deve ser criada um rota `DELETE /users/:user_id/del`, que receberá o id do usuário e realizará o `soft delete` do conta, ou seja, inativação mantendo os dados para histórico.  
**A única validação necessária é verificar o id é um uuid válido. Em caso negativo será lançada um `400 BAD REQUEST`. Já caso o usuário não exista, já esteja inativo, ou haja uma falha na operação, será lançada uma exceção `500 INTERNAL SERVER ERROR`**

## Additional context
- EPIC: #1 
- A lógica será feita no `service`.
- O `controller` será responsável por receber a requisição e acionar o `service`.

## Tasks
- [x] Criar interface de comunicação com o banco
- [x] Implementar lógica no `service`
- [x] Implementar método no `controller`
- [x] Configurar a rota no `router`
- [ ] Atualizar `CHANGELOG.md`
