### ISSUE TITLE
Criar `UserStats` no momento do cadastro do usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#50]
## Description
Atualmente somente o perfil do usuário está sendo criado no momento do cadastro, porém é necessário também criar seu `status` que evoluíra com o tempo. Nesse contexto, deve-se alterar o método de cadastro para também criar o `status` do usuário ao final do processo.  
A necessidade do `status` diz respeito mais ao cliente, porém pode-se fazer a mesma coisa para os administradores.

## Additional context
- Será necessário adaptar o serviço de usuário para suportar o gerenciamento do status.
	- Passar o `UserStatusRepository` no service.
	- Alterar configuração do módulo de usuário.

## Tasks

- [x] Criar interface com o banco de dados.
- [x] Implementar lógica no service.
	- [x] Ao criar o usuário, criar o respectivo `status`.
- [x] Atualizar módulo de usuário.
- [x] Atualizar `CHANGELOG.md`
