### ISSUE TITLE
Atualizar a experiência de usuário ao comprar Pokémons

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#51]
## Description
Para um cliente "subir de nível" ele compra Pokémons e ganha uma certa quantidade de experiência por isso. Nesse contexto é necessário realizar uma alteração na lógica da `finalização de compra`, onde ao executar o processo, será obtida o valor da experiência que o Pokémon gera, multiplicando-a pelo número de Pokémons comprados, resultando no valor total de experiência que o usuário obterá.
Ao final do processo de compra, a experiência do usuário deve ser atualizada.

## Additional context
- Será necessário adaptar o serviço de compras para suportar o `UserStats`
- Usar `UserStatsRepository.Update` para realizar a mudança.

## Tasks

- [x] Criar interface com o banco de dados para `UserStats`.
- [x] Implementar lógica no service de compra.
- [x] Atualizar módulo de compra para receber o `UserStatsRepository`.
- [x] Atualizar `CHANGELOG.md`
