### ISSUE TITLE
Obter Status do Usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#52]
## Description
Quando um usuário visualiza o seu perfil, ele deve também poder ver o seu status atual, incluindo sua experiência atual e tier.  Nesse contexto, deve-se devolver as informações do status juntamente com as informações do usuário ao requisitar a rota: `/users/:id`.
Também é interessante haver uma forma de obter somente o status do usuário, que pode ser feito via um método do repository de UserStats.

## Tasks

- [x] Atualizar o retorno da rota de `/users/:id (já feito por [#62](https://github.com/afmireski/garchop-api/pull/62))
- [x] Implementar rota `/users/:ids/status`
	- [x] Implementar interface com o banco de dados.
	- [x] Implementar lógica do service.
	- [x] Implementar handler do controller.
	- [x] Implementar rota.
- [x] Atualizar `CHANGELOG.md`
