### ISSUE TITLE
Implementar cadastro de recompensas

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#57]
## Description
Conforme um cliente sobe seu nível, ele pode ter acesso a diversas recompensas. Todavia, é necessário antes cadastrá-las no sistema.
Uma recompensa deve ter os seguintes paramêtros:
```go
type Reward struct {
	id string
	tier_id uint
	name string
	description string
	experience_required uint
	type PrizeTypeEnum
	prize Json
}
```

Inicialmente só haverá um único tipo de prêmio, Pokémons que não são vendidos normalmente.

## Additional context

- **Trabalhar no módulo de `rewards`**
- **Retornar nada, com código `201`**

### Body
```go
type InputBody struct {
	tier_id uint
	name string
	description string
	experience_required uint
	type PrizeTypeEnum
	prize Json
}
```

## Tasks

- [x] Implementar interfaces de conexão com o banco
- [x] Implementar lógica no service
- [x] Implementar chamada no controller
- [x] Implementar rota: `/rewards/new`
- [x] Atualizar `CHANGELOG.md`
