### ISSUE TITLE
Implementar listagem geral de recompensas

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#58]
## Description
A ideia das recompensas é atuar como um caminho de troféus. Nesse sentido, é interessante que ele seja exibido em uma tela única.

Como a mera exibição das recompensas não é algo sensível, pode ser feito com uma listagem simples: `GET /rewards`. Essa listagem deve exibir todas as informações da recompensa.

## Additional context

- **Trabalhar dentro do módulo de `rewards`**

## Tasks

- [x] Implementar interfaces de conexão com o banco
- [x] Implementar lógica no service
- [x] Implementar chamada no controller
- [x] Implementar rota: `/rewards`
- [x] Atualizar `CHANGELOG.md`
