### ISSUE TITLE
Implementar listagem específica de recompensas

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#59]
## Description

Conforme o cliente ganha experiência, ele pode adquirir recompensas do caminho de troféus. Nesse contexto é necessário criar uma rota que obtém o caminho de troféus e todas as recompensas que o usuário já obteve, indicando se o usuário já a desbloqueou e já as obteve.

## Additional context

- **Trabalhar dentro do módulo de `rewards`**

## Tasks

- [ ] Implementar interfaces de conexão com o banco
- [ ] Implementar lógica no service
- [ ] Implementar chamada no controller
- [ ] Implementar rota: `/rewards`
- [ ] Atualizar `CHANGELOG.md`
