### ISSUE TITLE
Implementar exclusão de recompensa

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#60]
## Description
Caso haja a necessidade de remover uma recompensa do caminho de troféus, deve-se permitir a um administrador remover recompensas, realizando um `soft delete`.

## Additional context
- **Somente ADMs podem requisitar essa rota**
- **Trabalhar dentro do módulo de `rewards`**

## Tasks

- [x] Implementar interfaces de conexão com o banco
- [x] Implementar lógica no service
- [x] Implementar chamada no controller
- [x] Implementar rota: `DELETE /rewards/:reward_id/remove`
- [x] Atualizar `CHANGELOG.md`
