### ISSUE TITLE
Implementar obtenção de recompensas por usuários

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#61]
## Description
Uma vez que o usuário atende certos requisitos, ele pode obter uma recompensa. Nesse contexto, um usuário, desde que logado e tendo o mínimo de experiência, deve poder reivindicar uma recompensa.

Após reivindicar, o prêmio é vinculado ao usuário. Por exemplo, se for um Pokémon, o usuário terá aquele Pokémon vinculado a ele.

## Additional context
- **O usuário deve estar logado**
- **O usuário deve ter o mínimo de experiência**
- **O usuário `deve ser um cliente`**
- **Pode-se obter o usuário de dentro do `token`**

## Tasks

- [x] Implementar interfaces de conexão com o banco
- [x] Implementar lógica no service
- [x] Implementar chamada no controller
- [x] Implementar rota: `/rewards/:reward_id/claim`
- [x] Atualizar `CHANGELOG.md`
