### ISSUE TITLE
Implementar listagem específica de Pokémons de um usuário

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#71]
## Description
Todo usuário terá uma espécie de Pokedex particular com todos os pokemons que ele comprou. Nesse contexto, é necessário criar uma rota para obter esses pokemons: `/pokedex`.

## Tasks

- [x] Implementar interfaces de conexão com o banco
- [x] Implementar lógica no service
- [x] Implementar chamada no controller
- [x] Implementar rota: `GET /pokedex`
- [x] Atualizar `CHANGELOG.md`
