### ISSUE TITLE
Implementar rota que permita o cadastro de um novo pokémon

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-api#9]
## Description
Os produtos do ecommerce constituem de Pokemons, que precisam ser colocados a venda. Esse gerenciamento é feito por um usuário administrador, que informa o nome do Pokémon, seu preço, tier e qual o estoque inicial.  
Com o nome do Pokémon devera ser realizada uma chamada para a PokeAPI obtendo as informações mais detalhadas sobre o monstrinho. Caso não seja encontrado nenhuma informação, retorna-se exceção dizendo que o Pokémon não existe.  
Os campos de `preço` e `quantidade` geram um novo registro cada um na tabela de `Price` e `Stock`, relacionando-os com o registro na tabela de Pokémon.

## Additional context

* **EPIC: #8**
* **Trabalhar considerando que módulo será `pokemon`**
* **Rota: /pokemon/new**

### Body
```typescript
type Input = {
	pokemon_name: string,
	tier_id: string,
	price: int,
	initial_stock: int,
}
```

### Restrições
- O tier deve existir.
- O preço deve ser positivo e maior que 0.
- O stock deve ser maior ou igual que 0.

## Tasks

- [x] Implementar tabelas no banco.
- [x] Criar interface de comunicação com o banco
- [x] Implementar lógica no `service`
- [x] Implementar método no `controller`
- [x] Configurar a rota no `router`
- [x] Atualizar `CHANGELOG.md`
